### ISSUE TITLE
可以不显示子文件夹的文件不

### ISSUE THREAD

**Issue by WenmuZhou** [JevenM/HTTP_SERVER#3]
您好，首先非常感谢您的项目，这里有两个小小的建议
1. 期望不显示子文件夹的文件，不然的话，页面显示的文件太多了
2. 希望显示文件大小时，可以按正常大小显示，如100M显示未100M，10G显示为10G，10kb显示为10kb，现在是统一显示未Byte的单位
另外，中文的显示好像乱码 
![image](https://user-images.githubusercontent.com/12406017/198630025-b55ec638-5f3e-441c-b5b3-9116250b4f68.png)

**Comment by JevenM** [comment]
感谢您的宝贵建议，有时间我会更新

**Comment by JevenM** [comment]
提出的问题已全部更新，至于中文乱码的问题，只要保证保存文件的时候不是ANSI而是utf-8，即可正确显示。
